name: Deploy PP Bot

on:
  push:
    branches:
      - main # Triggers deployment when you push to master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Local Changes
        run: |
          cd /home/ubuntu/PP_bot
          git pull origin main
          ./venv/bin/pip install -r requirements.txt
          sudo systemctl restart pp_bot.service
          sudo systemctl status pp_bot.service --no-pager
