name: Deploy PP Bot

on:
  push:
    branches:
      - main # Triggers deployment when you push to master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy Local Changes
        run: |
          cd /home/ubuntu/discord-bot
          git pull origin main
          docker build -t pp-bot .
          docker stop pp-bot || true
          docker rm pp-bot || true
          docker run -d --name pp-bot --restart unless-stopped --env-file .env pp-bot
